
# Loads default set of integrations. Do not remove.
default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

rest_command: !include brivo_api.yaml
light: !include brivo_light.yaml
lock: !include brivo_lock.yaml
sensor: !include sensor.yaml